---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdeployment
  labels:
    mytest: test
spec:
  selector:
    matchLabels:
      mytest: test
  replicas: 10
  template:
    metadata:
      labels:
        mytest: test
      name: mynginx
    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: Disabled
  name: fluxcannotdeleteme
data:
  myadata: red
