---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdeployment
  labels:
    mytest: test
spec:
  replicas: 3
  template:
    metadata:
      labels:
        mytest: test
      name: mynginx
    spec:
      containers:
      - name: nginx
        image: nginx
