---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: Override
  namespace: default
  name: testdeployment2
  labels:
    mytest: test
spec:
  selector:
    matchLabels:
      mytest: test
  replicas: 2
  template:
    metadata:
      namespace: webapp
      labels:
        mytest: test
      name: mynginx
    spec:
      containers:
      - name: nginx
        image: nginx

