---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdeployment
  labels:
    mytest: test
spec:
  selector:
    matchLabels:
      mytest: test
  replicas: 4
  template:
    metadata:
      labels:
        mytest: test
      name: mynginx
    spec:
      containers:
      - name: nginx
        image: nginx
