---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdeployment
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: Ignore
  labels:
    mytest: test
spec:
  selector:
    matchLabels:
      mytest: test
  replicas: 10
  template:
    metadata:
      labels:
        mytest: test
      name: mynginx
    spec:
      containers:
      - name: nginx
        image: nginx
